name: build-test

on: [push]

jobs:
  test:
    runs-on: codeberg-tiny
    steps:
      - uses: https://data.forgejo.org/actions/checkout@v4
      - run: |
          set -euo pipefail
          ZIG_URL="https://ziglang.org/builds/zig-x86_64-linux-0.16.0-dev.2368+380ea6fb5.tar.xz"
          curl -fL "${ZIG_URL}" -o zig.tar.xz
          tar -xf zig.tar.xz
          ZIG_DIR="zig-x86_64-linux-0.16.0-dev.2368+380ea6fb5"
          echo "$PWD/${ZIG_DIR}" >> "$GITHUB_PATH"
      - run: zig build test
