const std = @import("std");
const selection = @import("selection.zig");
const constants = @import("constants.zig");
const clip_pool = @import("clip_pool.zig");
const SampleStore = @import("../audio/sample_store.zig").SampleStore;

pub const ClipId = clip_pool.ClipId;

pub const NameField = struct {
    buf: [32]u8 = undefined,
    len: usize = 0,

    pub fn init(name: []const u8) NameField {
        var field = NameField{};
        field.set(name);
        return field;
    }

    pub fn set(self: *NameField, name: []const u8) void {
        const len = @min(name.len, self.buf.len);
        @memcpy(self.buf[0..len], name[0..len]);
        self.len = len;
    }

    pub fn get(self: *const NameField) []const u8 {
        return self.buf[0..self.len];
    }
};

pub const ClipState = enum {
    empty,
    stopped,
    queued,
    playing,
    recording,
    record_queued,
};

/// A session grid placement: a launcher that references a pooled clip.
/// Content, intrinsic length, name and color all live on the pooled `Clip`
/// (resolve via `State.clip_pool`); the slot owns only its launch state and
/// the handle. `.empty` state ⇔ `clip == .none`.
pub const ClipSlot = struct {
    state: ClipState = .empty,
    clip: ClipId = ClipId.none,
};

pub const RenameKind = enum {
    none,
    scene,
    clip,
};

pub const Track = struct {
    name: NameField = .{},
    volume: f32 = 0.8,
    /// Stereo balance, -1 = left, 0 = center, 1 = right.
    pan: f32 = 0,
    mute: bool = false,
    solo: bool = false,
    is_master: bool = false,

    pub fn init(name: []const u8) Track {
        var t = Track{};
        t.name.set(name);
        return t;
    }

    pub fn setName(self: *Track, name: []const u8) void {
        self.name.set(name);
    }

    pub fn getName(self: *const Track) []const u8 {
        return self.name.get();
    }
};

pub const MixerTarget = enum {
    track,
    master,
};

pub const master_track_index: usize = constants.max_tracks - 1;

pub const Scene = struct {
    name: NameField = .{},

    pub fn init(name: []const u8) Scene {
        var s = Scene{};
        s.name.set(name);
        return s;
    }

    pub fn setName(self: *Scene, name: []const u8) void {
        self.name.set(name);
    }

    pub fn getName(self: *const Scene) []const u8 {
        return self.name.get();
    }
};

/// Clipboard entry for clip copy/paste. Holds an independent, retained dupe
/// of the copied clip's content (freed when the clipboard is cleared), so the
/// copy survives deletion of the source and each paste re-dupes from it.
pub const ClipboardEntry = struct {
    src_track: usize,
    src_scene: usize,
    track_offset: i32,
    scene_offset: i32,
    state: ClipState,
    clip: ClipId,
};

pub const PianoCopyRequest = struct {
    src_track: usize,
    src_scene: usize,
    dst_track: usize,
    dst_scene: usize,
};

pub const OpenClipRequest = struct {
    track: usize,
    scene: usize,
};

pub const ClipSnapshot = struct {
    has_clip: bool = false,
    length_beats: f32 = 0,
    /// Pool handle captured at delete time so undo-request processing can read
    /// the deleted clip's content before the slot shift discards the handle.
    clip: ClipId = ClipId.none,
};

pub const TrackSnapshot = struct {
    name: NameField = .{},
    volume: f32 = 0,
    pan: f32 = 0,
    mute: bool = false,
    solo: bool = false,
};

pub const SceneSnapshot = struct {
    name: NameField = .{},
};

/// Types of undo requests generated by session view operations
pub const UndoRequestKind = enum {
    clip_create,
    clip_delete,
    clip_paste,
    clip_rename,
    track_add,
    track_delete,
    scene_add,
    scene_delete,
    scene_rename,
    track_volume,
};

/// Undo request for tracking state changes
pub const UndoRequest = struct {
    kind: UndoRequestKind,
    track: usize = 0,
    scene: usize = 0,
    src_track: usize = 0,
    src_scene: usize = 0,
    length_beats: f32 = 0,
    // For clip_delete: store the old clip state
    old_clip: ClipSlot = .{},
    // For track_volume
    old_volume: f32 = 0,
    new_volume: f32 = 0,
    // For track_delete
    track_data: TrackSnapshot = .{},
    track_clips: [constants.max_scenes]ClipSnapshot = @splat(.{}),
    // For scene_delete
    scene_data: SceneSnapshot = .{},
    scene_clips: [constants.max_tracks]ClipSnapshot = @splat(.{}),
    // For rename
    old_name: NameField = .{},
    new_name: NameField = .{},
};

/// Single clip move for undo
pub const ClipMoveEntry = struct {
    src_track: usize,
    src_scene: usize,
    dst_track: usize,
    dst_scene: usize,
};

/// Tracks the state of an active MIDI recording session
pub const RecordingState = struct {
    track: ?usize = null,
    scene: ?usize = null,
    start_beat: f32 = 0,
    queued_at_beat: f32 = 0,
    target_length_beats: f32 = constants.default_clip_bars * constants.beats_per_bar, // 4 bars
    note_start_beats: [128]?f32 = @splat(null), // Track held notes
    note_start_velocities: [128]?f32 = @splat(null),
    is_new_clip: bool = false,

    pub fn isRecording(self: *const RecordingState) bool {
        return self.track != null;
    }

    pub fn reset(self: *RecordingState) void {
        self.track = null;
        self.scene = null;
        self.start_beat = 0;
        self.queued_at_beat = 0;
        self.target_length_beats = constants.default_clip_bars * constants.beats_per_bar;
        self.note_start_beats = @splat(null);
        self.note_start_velocities = @splat(null);
        self.is_new_clip = false;
    }
};

pub const StopRecordingMode = enum {
    stop,
    loop,
};

pub const SessionView = struct {
    allocator: std.mem.Allocator,

    // Back-references into the owning `State` (wired once after State reaches
    // its final address; see `State.wireInternalRefs`). Session ops resolve
    // and mutate pooled clip content through these.
    clip_pool: *clip_pool.ClipPool = undefined,
    sample_store: *SampleStore = undefined,

    // Grid data
    tracks: [constants.max_tracks]Track = undefined,
    scenes: [constants.max_scenes]Scene = undefined,
    clips: [constants.max_tracks][constants.max_scenes]ClipSlot = undefined,
    track_count: usize = 4,
    scene_count: usize = 8,
    mixer_target: MixerTarget = .track,

    // Selection - simple 2D bool array
    clip_selected: [constants.max_tracks][constants.max_scenes]bool = @splat(@splat(false)),
    primary_track: usize = 0,
    primary_scene: usize = 0,
    drag_select: selection.DragSelectState = .{},

    // Clipboard
    clipboard: std.ArrayListUnmanaged(ClipboardEntry) = .empty,
    clipboard_origin_track: usize = 0,
    clipboard_origin_scene: usize = 0,
    // Piano clip copy requests (processed by document/cmd_undo.zig)
    piano_copy_requests: [constants.max_tracks * constants.max_scenes]PianoCopyRequest = undefined,
    piano_copy_count: usize = 0,
    pending_piano_copies: bool = false,

    // Drag move state
    drag_moving: bool = false,
    drag_start_track: usize = 0,
    drag_start_scene: usize = 0,
    drag_target_track: ?usize = null, // Where clips will move to (preview)
    drag_target_scene: ?usize = null,
    // Cell positions for accurate ghost rendering (updated during clip rendering)
    cell_positions: [constants.max_tracks][constants.max_scenes][2]f32 = @splat(@splat(.{ 0, 0 })),

    // Playback state
    queued_scene: [constants.max_tracks]?usize = @splat(null),
    open_clip_request: ?OpenClipRequest = null,
    start_playback_request: bool = false,
    reset_playhead_request: bool = false,

    // Undo requests are staged during a UI frame, then consumed by
    // document/cmd_undo.zig. This must grow for bulk edits so displaced pooled
    // clips always reach their ownership hand-off.
    undo_requests: std.ArrayListUnmanaged(UndoRequest) = .empty,

    // Clip move undo (separate since it can involve multiple clips)
    clip_move_requests: [constants.max_tracks * constants.max_scenes]ClipMoveEntry = undefined,
    clip_move_count: usize = 0,
    // Also used to signal document undo to move piano clips
    pending_piano_moves: bool = false,

    // Volume drag tracking for undo
    volume_drag_track: ?usize = null,
    volume_drag_start: f32 = 0,

    // Recording state
    recording: RecordingState = .{},
    armed_track: ?usize = null, // Track armed for recording (only one at a time)
    finalize_recording_track: ?usize = null, // Track to finalize notes on
    finalize_recording_scene: ?usize = null, // Scene to finalize notes on
    clear_piano_clip_request: ?OpenClipRequest = null, // Clear piano notes (new MIDI recording)
    /// Drop sample on slot so MIDI owns the cell (hybrid exclusive content).
    claim_midi_slot_request: ?OpenClipRequest = null,

    // Render-time hover tracking (updated during clip slot rendering for accurate hit detection)
    render_hover_track: ?usize = null,
    render_hover_scene: ?usize = null,
    render_hover_has_content: bool = false,

    // Inline rename (scene header / clip slot)
    rename_kind: RenameKind = .none,
    rename_track: usize = 0,
    rename_scene: usize = 0,
    rename_buf: [32:0]u8 = @splat(0),
    rename_old: NameField = .{},
    rename_focus: bool = false,

    pub fn emitUndoRequest(self: *SessionView, req: UndoRequest) bool {
        self.undo_requests.append(self.allocator, req) catch return false;
        return true;
    }
};

test {
    // Pull the clip-pool module into the test graph so its unit tests run
    // under `zig build test`. Nothing wires it into runtime.
    _ = @import("clip_pool.zig");
}

test "undo request staging grows for bulk edits" {
    var view = SessionView{ .allocator = std.testing.allocator };
    defer view.undo_requests.deinit(std.testing.allocator);

    for (0..17) |track| {
        try std.testing.expect(view.emitUndoRequest(.{
            .kind = .track_add,
            .track = track,
        }));
    }
    try std.testing.expectEqual(@as(usize, 17), view.undo_requests.items.len);
}
